title: Antioch Baptist Church
email: info@antiochbaptist.online
description: "Website for Antioch Baptist Church in Dewy Rose, GA"
baseurl: ""
url: "https://antiochbaptist.online"

# twitter_username:
facebook_username: 100064530106496
sms_phonenumber: 8334587182

# Build settings
markdown: kramdown
